// Generated by scripts/gen-abi.ts from shared/abi/PerplExchange.json. Do not edit.
export const perplExchangeAbi = [
  {
    "type": "function",
    "name": "createAccount",
    "inputs": [
      {
        "name": "amountCNS",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "depositCollateral",
    "inputs": [
      {
        "name": "amountCNS",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "execOrder",
    "inputs": [
      {
        "name": "orderDesc",
        "type": "tuple",
        "internalType": "struct OrderDesc",
        "components": [
          {
            "name": "orderDescId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "perpId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "orderType",
            "type": "uint8",
            "internalType": "enum OrderDescEnum"
          },
          {
            "name": "orderId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pricePNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lotLNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "expiryBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "postOnly",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "fillOrKill",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "immediateOrCancel",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "maxMatches",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "leverageHdths",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lastExecutionBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amountCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxNegPnlCollatBPS",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "signature",
        "type": "tuple",
        "internalType": "struct OrderSignature",
        "components": [
          {
            "name": "perpId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "orderId",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getAccountByAddr",
    "inputs": [
      {
        "name": "accountAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "accountInfo",
        "type": "tuple",
        "internalType": "struct AccountInfo",
        "components": [
          {
            "name": "accountId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "balanceCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lockedBalanceCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "frozen",
            "type": "uint8",
            "internalType": "enum FreezeStatusEnum"
          },
          {
            "name": "accountAddr",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "positions",
            "type": "tuple",
            "internalType": "struct PositionBitMap",
            "components": [
              {
                "name": "bank1",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bank2",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bank3",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bank4",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAccountById",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "accountInfo",
        "type": "tuple",
        "internalType": "struct AccountInfo",
        "components": [
          {
            "name": "accountId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "balanceCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lockedBalanceCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "frozen",
            "type": "uint8",
            "internalType": "enum FreezeStatusEnum"
          },
          {
            "name": "accountAddr",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "positions",
            "type": "tuple",
            "internalType": "struct PositionBitMap",
            "components": [
              {
                "name": "bank1",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bank2",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bank3",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bank4",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMinAccountOpenCNS",
    "inputs": [],
    "outputs": [
      {
        "name": "minAccountOpenCNS",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPerpetualInfoV2",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "perpetualInfo",
        "type": "tuple",
        "internalType": "struct PerpetualInfoV2",
        "components": [
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "symbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "priceDecimals",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lotDecimals",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "linkFeedId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "priceTolPer100K",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "marginTol",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "marginTolDecimals",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "refPriceMaxAgeSec",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "positionBalanceCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "insuranceBalanceCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "markPNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "markTimestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lastPNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lastTimestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "oraclePNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "oracleTimestampSec",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "longOpenInterestLNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "shortOpenInterestLNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "fundingStartBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "fundingRatePct100k",
            "type": "int16",
            "internalType": "int16"
          },
          {
            "name": "absFundingClampPctPer100K",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum PerpStatusEnum"
          },
          {
            "name": "basePricePNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxBidPriceONS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minBidPriceONS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxAskPriceONS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minAskPriceONS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "numOrders",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "ignOracle",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "fundingSumScalingExp",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPositionV2",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "positionInfo",
        "type": "tuple",
        "internalType": "struct PositionInfoV2",
        "components": [
          {
            "name": "accountId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "nextNodeId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "prevNodeId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "positionType",
            "type": "uint8",
            "internalType": "enum PositionEnum"
          },
          {
            "name": "depositCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pricePNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lotLNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "entryBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pnlCNS",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "deltaPnlCNS",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "premiumPnlCNS",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "priceResiduePNSQ16",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "markPricePNS",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "markPriceValid",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPositionsV2",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "pageStartPositionId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "positionsPerPage",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "positions",
        "type": "tuple[]",
        "internalType": "struct PositionInfoV2[]",
        "components": [
          {
            "name": "accountId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "nextNodeId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "prevNodeId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "positionType",
            "type": "uint8",
            "internalType": "enum PositionEnum"
          },
          {
            "name": "depositCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pricePNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lotLNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "entryBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pnlCNS",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "deltaPnlCNS",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "premiumPnlCNS",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "priceResiduePNSQ16",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "numPositions",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "markPricePNS",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "markPriceValid",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isPriceAdministrator",
    "inputs": [
      {
        "name": "anAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "numberOfAccounts",
    "inputs": [],
    "outputs": [
      {
        "name": "numAccounts",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setIgnOracle",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "ignOracle",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "updateMarkPricePNS",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "markPricePNS",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "withdrawCollateral",
    "inputs": [
      {
        "name": "amountCNS",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AccountCreated",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "id",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MarkUpdated",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "pricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PositionClosed",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "positionType",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum PositionEnum"
      },
      {
        "name": "pricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "deltaPnlCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "fundingCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PositionDecreased",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "positionType",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum PositionEnum"
      },
      {
        "name": "startDepositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "endDepositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "startLotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "endLotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "deltaPnlCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "fundingCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PositionDeleveraged",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "forceClose",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "positionType",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum PositionEnum"
      },
      {
        "name": "entryPricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "markPricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "deleveragePricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "deltaPnlCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "fundingCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "startDepositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "endDepositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "startLotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "endLotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "amountCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "balanceCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PositionDeleveragedV2",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "forceClose",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "positionType",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum PositionEnum"
      },
      {
        "name": "entryPricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "markPricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "deleveragePricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "deltaPnlCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "fundingCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "startDepositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "endDepositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "startLotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "endLotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "amountCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "balanceCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "priceResiduePNSQ16",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PositionIncreased",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "positionType",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum PositionEnum"
      },
      {
        "name": "leverageHdths",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "startDepositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "endDepositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "pnlCollateralizedCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "premiumPnlSettledCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "maxNegPnlCollatBPS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "pricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "startLotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "endLotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "insFeeCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "protFeeCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PositionIncreasedV2",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "positionType",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum PositionEnum"
      },
      {
        "name": "leverageHdths",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "startDepositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "endDepositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "pnlCollateralizedCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "premiumPnlSettledCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "maxNegPnlCollatBPS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "pricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "startLotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "endLotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "insFeeCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "protFeeCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "priceResiduePNSQ16",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PositionInverted",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "positionType",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum PositionEnum"
      },
      {
        "name": "leverageHdths",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "startDepositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "endDepositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "pnlCollateralizedCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "pricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "startLotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "endLotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "deltaPnlCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "fundingCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "insFeeCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "protFeeCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PositionLiquidated",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "posAccountId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "positionType",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum PositionEnum"
      },
      {
        "name": "markPricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "liqPricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "liqLotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "posLotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "deltaPnlCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "fundingCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "posAmountCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "posDepositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "accAmountCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "accBalanceCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "onOrderBook",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PositionOpened",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "positionType",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum PositionEnum"
      },
      {
        "name": "leverageHdths",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "depositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "pnlCollateralizedCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "pricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "lotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "insFeeCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "protFeeCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PositionOpenedV2",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "positionType",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum PositionEnum"
      },
      {
        "name": "leverageHdths",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "depositCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "pnlCollateralizedCNS",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      },
      {
        "name": "pricePNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "lotLNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "insFeeCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "protFeeCNS",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "priceResiduePNSQ16",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  }
] as const;
