// Regenerates src/abi/*.ts from ../shared/abi/*.json so viem can infer types (`as const`).
// The Perpl Exchange ABI is filtered to the entries the engine uses, plus every error for revert decoding.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const shared = join(root, '..', 'shared', 'abi');
const out = join(root, 'src', 'abi');
mkdirSync(out, { recursive: true });

type Entry = { type: string; name?: string };
const load = (f: string): Entry[] => {
  const j = JSON.parse(readFileSync(join(shared, f), 'utf8'));
  return Array.isArray(j) ? j : j.abi;
};

const perplKeep = new Set([
  'execOrder', 'getPositionV2', 'getPositionsV2', 'getPerpetualInfoV2', 'getAccountById', 'getAccountByAddr',
  'createAccount', 'depositCollateral', 'withdrawCollateral', 'getMinAccountOpenCNS', 'updateMarkPricePNS',
  'setIgnOracle', 'isPriceAdministrator', 'owner', 'numberOfAccounts',
  'PositionOpened', 'PositionOpenedV2', 'PositionIncreased', 'PositionIncreasedV2', 'PositionDecreased',
  'PositionClosed', 'PositionInverted', 'PositionLiquidated', 'PositionDeleveraged', 'PositionDeleveragedV2',
  'MarkUpdated', 'AccountCreated',
]);

const files: Array<[string, string, (e: Entry) => boolean]> = [
  ['MirrorAccount.json', 'mirrorAccountAbi', () => true],
  ['MirrorAccountFactory.json', 'mirrorAccountFactoryAbi', () => true],
  ['KeeperRegistry.json', 'keeperRegistryAbi', () => true],
  ['PerplExchange.json', 'perplExchangeAbi', (e) => e.type === 'error' || perplKeep.has(e.name ?? '')],
];

for (const [file, name, keep] of files) {
  const abi = load(file).filter(keep);
  const ts = `// Generated by scripts/gen-abi.ts from shared/abi/${file}. Do not edit.\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(out, file.replace('.json', '.ts')), ts);
  console.log(`${name}: ${abi.length} entries`);
}
