#!/usr/bin/env python3
"""Assemble docs/submission.md from docs/submission/fields/, in the portal's field order.

Counts characters the way the portal's text fields do (UTF-16 code units, like JavaScript string
length) and exits non-zero if any field is over its limit.

Usage: python3 docs/submission/build.py
"""
import datetime
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent
FIELDS = ROOT / "fields"
OUT = ROOT.parent / "submission.md"


def read(name: str) -> str:
    return (FIELDS / name).read_text(encoding="utf-8").strip("\n")


def count(text: str) -> int:
    return len(text.encode("utf-16-le")) // 2


# (section, label, file or None, limit or None, note)
FORM = [
    ("Primary track", "Primary track *", None, None, "Onchain Finance & Trading (selected and saved in the portal)."),
    ("Project details", "Project logo *", None, None,
     "Supplied by Jagadeesh: PNG, JPG or WEBP, at least 500 px, up to 4 million pixels, max 2 MB. PENDING."),
    ("Project details", "Project name *", "02-project-name.txt", 120, ""),
    ("Project details", "One-line description *", "03-one-liner.txt", 200, ""),
    ("Project details", "Description *", "04-description.txt", 8000, ""),
    ("Project details", "Please describe the go-to-market and user acquisition strategy for your product. *",
     "05-go-to-market.txt", 8000, "Matches docs/traction-plan.md."),
    ("Project details", "GitHub repository *", "06-github.txt", None, "URL field."),
    ("Demo and pitch", "Live product *", "07-live-product.txt", None, "URL field. Must run on Monad mainnet or testnet."),
    ("Demo and pitch", "Technical demo video *", "08-demo-video.txt", None, "URL field. Up to 3 minutes."),
    ("Demo and pitch", "Pitch video *", "09-pitch-video.txt", None, "URL field. Up to 2 minutes."),
    ("Demo and pitch", "Judge access instructions (optional)", "10-judge-access.txt", 8000,
     "Private to the team, judges and organizers."),
]
PROMO = [
    ("Product advertisement (optional)", "12-product-ad.txt", "URL field. Up to 30 seconds."),
    ("X profile link for your project (optional)", "13-x-profile.txt", "URL field."),
]


def main() -> int:
    errors = []
    lines = [
        "# Metropolis submission: field text",
        "",
        "Generated by `docs/submission/build.py` from `docs/submission/fields/`. Edit the field files, then rebuild.",
        "Fields are in the portal's order. Character counts use the portal's counting (UTF-16 code units).",
        "Anything not built yet is marked PENDING. The portal has no final submit: what is saved at the deadline",
        "(14 Oct 2026, 03:59 UTC) is the entry, so keep the saved form in sync with this file.",
        "",
        f"Last built: {datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
    ]
    section = None
    for sec, label, fname, limit, note in FORM:
        if sec != section:
            lines += [f"## {sec}", ""]
            section = sec
        lines.append(f"### {label}")
        if fname is None:
            lines += [note, ""]
            continue
        text = read(fname)
        n = count(text)
        lim = f" / {limit:,}" if limit else ""
        status = ""
        if limit and n > limit:
            status = "  **OVER LIMIT**"
            errors.append(f"{label}: {n} > {limit}")
        meta = f"Characters: {n:,}{lim}{status}." + (f" {note}" if note else "")
        lines += [meta, "", "```text", text, "```", ""]

    # Bounties
    lines += ["## Bounties", "",
              "Each bounty's questions appear in the portal only after the bounty is added, so their limits are not",
              "known yet. Question wording is from each bounty page's \"ASKED FOR AT SUBMISSION\" section.", ""]
    btxt = read("11-bounties.md")
    for block in re.split(r"(?m)^(?=## )", btxt):
        if not block.strip():
            continue
        def repl(m):
            ans = m.group(1).strip("\n")
            return f"Characters: {count(ans):,}.\n\n```text\n{ans}\n```"
        block = re.sub(r"<!--answer-->\n(.*?)\n<!--/answer-->", repl, block, flags=re.S)
        block = re.sub(r"(?m)^## ", "### ", block)
        block = re.sub(r"(?m)^### Q", "#### Q", block)
        lines += [block.rstrip(), ""]

    lines += ["## Optional promotion", ""]
    for label, fname, note in PROMO:
        text = read(fname)
        lines += [f"### {label}", f"Characters: {count(text):,}. {note}", "", "```text", text, "```", ""]

    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    if errors:
        print("Over limit:\n  " + "\n  ".join(errors), file=sys.stderr)
        return 1
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
